# Generated by Django 5.1.1 on 2024-10-05 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_agenceemballage'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenceemballage',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
