# Generated by Django 5.1.1 on 2024-10-05 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_agenceemballage_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenceventebillet',
            name='url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='compagnietransport',
            name='url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='programmevoyage',
            name='url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='transporteurcolis',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
