# Generated by Django 5.1.1 on 2024-10-05 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_agenceventebillet_url_compagnietransport_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programmevoyage',
            name='url',
        ),
    ]
