# Generated by Django 5.1.1 on 2024-10-11 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0011_alter_offre_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offre',
            name='description',
            field=models.TextField(max_length=500),
        ),
    ]
